### ISSUE TITLE
Problems with lifecycle policy

### ISSUE THREAD

**Issue by 35blaze** [zoitech/terraform-gcp-gcs#1]
Hello,
I receive an error when creating a GCS bucket.
`googleapi: Error 400: Invalid value for: delete is not a valid value, invalid`
Can the lifecycle rule be optional.

**Comment by Geartrixy** [comment]
Hi Desiree,

after investigating and testing, it appears the value for the lifecycle action is case sensitive. 

This was amended from "delete" to "Delete". The changed has been pushed and is in next release:

source = "git::https://github.com/zoitech/terraform-gcp-gcs.git?ref=v0.0.2"

Thanks!
Geartrixy
